### ISSUE TITLE
Addon fails to install/enable with 4.4-alpha

### ISSUE THREAD

**Issue by sambler** [BrendanParmer/NodeToPython#134]
Attempting to install the node-to-python addon using master build (4.4-alpha 10/11/24) and getting errors. Works with 4.2-release.

There would appear to be a naming issue. website: `node-to-python` blender_manifest.toml: `node_to_python` github: `NodeToPython`

1. Click install in get-extensions. In the terminal I get `Package should have been installed but not found: node_to_python`

2. Manual install, copy files from github repo into extension folder. I get the following in the terminal -

```Extension: unexpected error detecting cache, this is is a bug!
Traceback (most recent call last):
  File "build_dir/bin/4.4/scripts/modules/addon_utils.py", line 1179, in _initialize_extensions_compat_data
    updated, wheel_list = _initialize_extensions_compat_ensure_up_to_date(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "build_dir/bin/4.4/scripts/modules/addon_utils.py", line 1102, in _initialize_extensions_compat_ensure_up_to_date
    cache_data = _extension_compat_cache_create(blender_id, extensions_enabled, wheel_list, print_debug)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "build_dir/bin/4.4/scripts/modules/addon_utils.py", line 1036, in _extension_compat_cache_create
    if (error := bl_pkg.manifest_compatible_with_wheel_data_or_error(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "build_dir/bin/4.4/scripts/addons_core/bl_pkg/__init__.py", line 121, in manifest_compatible_with_wheel_data_or_error
    if isinstance(python_versions_test := python_versions_from_wheels(wheel_files), str):
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "build_dir/bin/4.4/scripts/addons_core/bl_pkg/bl_extension_utils.py", line 843, in python_versions_from_wheels
    result = fn(wheel_files)
             ^^^^^^^^^^^^^^^
  File "build_dir/bin/4.4/scripts/addons_core/bl_pkg/cli/blender_ext.py", line 2263, in python_versions_from_wheels
    assert False, "unreachable"
AssertionError: unreachable
Skipping package with inconsistent name: "NodeToPython" mismatch "node_to_python"

```

3. Manual install and rename to node_to_python. Blender finds the addon, I get an error enabling -

```Extension: unexpected error detecting cache, this is is a bug!
Traceback (most recent call last):
  File "build_dir/bin/4.4/scripts/modules/addon_utils.py", line 1179, in _initialize_extensions_compat_data
    updated, wheel_list = _initialize_extensions_compat_ensure_up_to_date(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "build_dir/bin/4.4/scripts/modules/addon_utils.py", line 1102, in _initialize_extensions_compat_ensure_up_to_date
    cache_data = _extension_compat_cache_create(blender_id, extensions_enabled, wheel_list, print_debug)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "build_dir/bin/4.4/scripts/modules/addon_utils.py", line 1036, in _extension_compat_cache_create
    if (error := bl_pkg.manifest_compatible_with_wheel_data_or_error(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "build_dir/bin/4.4/scripts/addons_core/bl_pkg/__init__.py", line 121, in manifest_compatible_with_wheel_data_or_error
    if isinstance(python_versions_test := python_versions_from_wheels(wheel_files), str):
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "build_dir/bin/4.4/scripts/addons_core/bl_pkg/bl_extension_utils.py", line 843, in python_versions_from_wheels
    result = fn(wheel_files)
             ^^^^^^^^^^^^^^^
  File "build_dir/bin/4.4/scripts/addons_core/bl_pkg/cli/blender_ext.py", line 2263, in python_versions_from_wheels
    assert False, "unreachable"
AssertionError: unreachable
Traceback (most recent call last):
  File "build_dir/bin/4.4/scripts/modules/addon_utils.py", line 407, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "build_dir/bin/portable/extensions/blender_org/node_to_python/__init__.py", line 18, in <module>
    from . import compositor
  File "build_dir/bin/portable/extensions/blender_org/node_to_python/compositor/__init__.py", line 6, in <module>
    from . import operator
  File "build_dir/bin/portable/extensions/blender_org/node_to_python/compositor/operator.py", line 5, in <module>
    from ..ntp_operator import NTP_Operator, INDEX
  File "build_dir/bin/portable/extensions/blender_org/node_to_python/ntp_operator.py", line 4, in <module>
    from bpy_types import bpy_types
ImportError: cannot import name 'bpy_types' from 'bpy_types' (build_dir/bin/4.4/scripts/modules/bpy_types.py)
Extension: unexpected error detecting cache, this is is a bug!
Traceback (most recent call last):
  File "build_dir/bin/4.4/scripts/modules/addon_utils.py", line 1179, in _initialize_extensions_compat_data
    updated, wheel_list = _initialize_extensions_compat_ensure_up_to_date(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "build_dir/bin/4.4/scripts/modules/addon_utils.py", line 1102, in _initialize_extensions_compat_ensure_up_to_date
    cache_data = _extension_compat_cache_create(blender_id, extensions_enabled, wheel_list, print_debug)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "build_dir/bin/4.4/scripts/modules/addon_utils.py", line 1036, in _extension_compat_cache_create
    if (error := bl_pkg.manifest_compatible_with_wheel_data_or_error(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "build_dir/bin/4.4/scripts/addons_core/bl_pkg/__init__.py", line 121, in manifest_compatible_with_wheel_data_or_error
    if isinstance(python_versions_test := python_versions_from_wheels(wheel_files), str):
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "build_dir/bin/4.4/scripts/addons_core/bl_pkg/bl_extension_utils.py", line 843, in python_versions_from_wheels
    result = fn(wheel_files)
             ^^^^^^^^^^^^^^^
  File "build_dir/bin/4.4/scripts/addons_core/bl_pkg/cli/blender_ext.py", line 2263, in python_versions_from_wheels
    assert False, "unreachable"
AssertionError: unreachable

```

**Comment by luckychris** [comment]
same here, but with this error: Package should have been installed but not found: node_to_python
