### ISSUE TITLE
[BUG] bpy.types.NodeTreeInterface SocketMenu only exists in versions greater than Blender 4.1

### ISSUE THREAD

**Issue by LPG-VERSION** [BrendanParmer/NodeToPython#140]
bpy.types.NodeTreeInterface SocketMenu only exists in versions greater than Blender 4.1

OS:WindowsX64
blender version:4.0.2
bug:when clicking on a material with a custom node group in the material panel, an exception occurs. just create a custom node group and it will be reproduced
addon_version:3.3.0

exception:
  Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\NodeToPython\shader\operator.py", line 171, in execute
    self._process_node_tree(node_tree)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\NodeToPython\shader\operator.py", line 108, in _process_node_tree
    self._tree_interface_settings(ntp_nt)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\NodeToPython\ntp_operator.py", line 789, in _tree_interface_settings
    self._process_items(None, panel_dict, items_processed, ntp_nt)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\NodeToPython\ntp_operator.py", line 771, in _process_items
    self._create_socket(item, parent, panel_dict, ntp_nt)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\NodeToPython\ntp_operator.py", line 653, in _create_socket
    self._set_tree_socket_defaults(socket, socket_var)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\NodeToPython\ntp_operator.py", line 572, in _set_tree_socket_defaults
    if type(socket_interface) is bpy.types.NodeTreeInterfaceSocketMenu:
AttributeError: 'module' object has no attribute 'NodeTreeInterfaceSocketMenu'

**Comment by BrendanParmer** [comment]
Thanks for the bug report! I was able to reproduce the issue, and it's been resolved with #141

**Comment by LPG-VERSION** [comment]
this is a great plugin that solves many problems,thank you for your work
