### ISSUE TITLE
Does this need a custom node?

### ISSUE THREAD

**Issue by Blender-zbq** [BrendanParmer/NodeToPython#17]
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.3/scripts/modules/addon_utils.py", line 421, in disable
    mod.unregister()
  File "/Users/zhangbinqi/Library/Application Support/Blender/3.3/scripts/addons/node_to_python.py", line 464, in unregister
    bpy.utils.unregister_class(NodeToPython)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

**Comment by BrendanParmer** [comment]
Hi @Blender-zbq, what you were trying to accomplish when you got this error? Steps to reproduce it would be even better for helping me track down what caused this
